...

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -24,7 +24,7 @@ fetch_meteor() {
 #  curl -o "$CACHE_DIR/$PACKAGE" "http://d3sqy0vbqsdhku.cloudfront.net/${PACKAGE}"
 #  echo "`ls -l $CACHE_DIR/$PACKAGE`"
   echo 'Installing Meteor'
-  echo "`curl https://install.meteor.com/ | sh`" || echo FAIL
+  echo "`curl https://install.meteor.com/ | sh 2>&1`" || echo FAIL
 
 #  echo "Unpacking meteor to $METEOR_HOME from $CACHE_DIR/$PACKAGE"
 #  [ ! -d "$METEOR_HOME" ] && mkdir -p "$METEOR_HOME"
